name: Deploy

on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Make env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_SNOWPACK_PUBLIC_GRAPHQL_URL: ${{ secrets.SNOWPACK_PUBLIC_GRAPHQL_URL }}
          envkey_SNOWPACK_PUBLIC_GOOGLE_LOCATION_API_KEY: ${{ secrets.SNOWPACK_PUBLIC_GOOGLE_LOCATION_API_KEY }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jana19/treelative-client:prod
      - name: Redeploy on Portainer
        uses: wei/curl@master
        with:
          args: -X POST ${{ secrets.DEPLOY_CLIENT }}
